name: Movies Web For All
run-name: project checks
on: [push]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting ts
        run: npm run lint:ts
      - name: linting scss
        run: npm run lint:scss
      - name: run unit tests
        run: npm run test:jest
      - name: run storybook
        run: npm run storybook
      - name: run screenshot tests
        run: npm run test:loki
