name: Movies Web For All
run-name: project checks
on: [push, pull]
jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
    matrix:
      node-version: [20.x]

    steps:

      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: intsall modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting ts
        run: npm run lint:ts
      - name: linting scss
        run: npm run lint:scss
      - name: run unit tests
        run: npm run test:jest
      - name: run screenshot tests
        run: npm run test:loki
